import { CategoryItem } from '../types';
import { colors } from '../theme/colors';

export const CATEGORIES: CategoryItem[] = [
  {
    id: 'Animals',
    title: 'Animals',
    subtitle: '🐶 Woof & Meow',
    icon: '🐶',
    bgColor: colors.categoryAnimals,
    accentColor: colors.primary,
  },
  {
    id: 'Fruits',
    title: 'Fruits',
    subtitle: '🍎 Yummy Bites',
    icon: '🍎',
    bgColor: colors.categoryFruits,
    accentColor: colors.primaryDark,
  },
  {
    id: 'Colors',
    title: 'Colors',
    subtitle: '🎨 Bright World',
    icon: '🎨',
    bgColor: colors.categoryColors,
    accentColor: colors.accentPurple,
  },
  {
    id: 'Numbers',
    title: 'Numbers',
    subtitle: '🔢 1, 2, 3!',
    icon: '🔢',
    bgColor: colors.categoryNumbers,
    accentColor: colors.accentGreen,
  },
  {
    id: 'ABC',
    title: 'ABC',
    subtitle: '🔤 Learn Letters',
    icon: '🔤',
    bgColor: colors.categoryAbc,
    accentColor: colors.accentBlue,
  },
  {
    id: 'Vehicles',
    title: 'Vehicles',
    subtitle: '🚗 Beep Beep!',
    icon: '🚗',
    bgColor: colors.categoryVehicles,
    accentColor: colors.accentOrange,
  },
  {
    id: 'Body',
    title: 'My Body',
    subtitle: '👀 Eyes & Ears',
    icon: '👀',
    bgColor: colors.categoryBody,
    accentColor: colors.accentPink,
  },
  {
    id: 'Family',
    title: 'My Family',
    subtitle: '👨‍👩‍👦 Mama & Baba',
    icon: '👨‍👩‍👦',
    bgColor: colors.categoryFamily,
    accentColor: colors.primary,
  },
  {
    id: 'Sounds',
    title: 'Sounds',
    subtitle: '🔊 Listen & Play',
    icon: '🔊',
    bgColor: colors.categorySounds,
    accentColor: colors.secondary,
  },
  {
    id: 'Songs',
    title: 'Songs',
    subtitle: '🎵 Sing Along',
    icon: '🎵',
    bgColor: colors.categorySongs,
    accentColor: colors.accentPurple,
  },
  {
    id: 'Discovery',
    title: 'Discovery',
    subtitle: '🌎 Explore World',
    icon: '🌎',
    bgColor: colors.categoryDiscovery,
    accentColor: colors.accentGreen,
  },
  {
    id: 'Games',
    title: 'Games',
    subtitle: '🎮 Easy Play',
    icon: '🎮',
    bgColor: colors.categoryGames,
    accentColor: colors.secondaryDark,
  },
  {
    id: 'Parents',
    title: 'Parent Area',
    subtitle: '🔒 Safety & Stats',
    icon: '🔒',
    bgColor: colors.categoryParents,
    accentColor: colors.textDark,
  },
  {
    id: 'Settings',
    title: 'Settings',
    subtitle: '⚙️ Audio & Visuals',
    icon: '⚙️',
    bgColor: colors.categorySettings,
    accentColor: colors.textMuted,
  },
];
